name       : blueprint-compiler
version    : 0.8.1
release    : 3
source     :
    - https://gitlab.gnome.org/jwestman/blueprint-compiler/-/archive/v0.8.1/blueprint-compiler-v0.8.1.tar.gz : 9207697cfac6e87a3c0ccf463be1a95c3bd06aa017c966a7e352ad5bc486cf3c
license    : GPL-3.0-or-later
homepage   : https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/
component  : programming.tools
summary    : Markup language and compiler for GTK 4 user interfaces
description: |
    Blueprint is a markup language and compiler for GTK 4 user interfaces. It has modern IDE features like code completion and hover documentation, and the compiler points out mistakes early on so you can focus on making your app look amazing.
rundeps    :
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - /*
