name       : blueprint-compiler
version    : 0.4.0
release    : 1
source     :
    - https://gitlab.gnome.org/jwestman/blueprint-compiler/-/archive/v0.4.0/blueprint-compiler-v0.4.0.tar.gz : c1a5efd8562aca7df259679c6d9cd067ea2a78372069fcc01985619ec3963d8f
license    : GPL-3.0-or-later
homepage   : https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/
component  : programming.tools
summary    : Markup language and compiler for GTK 4 user interfaces
description: |
    Blueprint is a markup language and compiler for GTK 4 user interfaces. It has modern IDE features like code completion and hover documentation, and the compiler points out mistakes early on so you can focus on making your app look amazing.
rundeps    :
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - /*
