name       : blueprint-compiler
version    : 0.6.0
release    : 2
source     :
    - https://gitlab.gnome.org/jwestman/blueprint-compiler/-/archive/v0.6.0/blueprint-compiler-v0.6.0.tar.gz : c9e3652b66803c1de6a24b71f4fa4638b32260b4b04b93c2f3d958e1ce2a175e
license    : GPL-3.0-or-later
homepage   : https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/
component  : programming.tools
summary    : Markup language and compiler for GTK 4 user interfaces
description: |
    Blueprint is a markup language and compiler for GTK 4 user interfaces. It has modern IDE features like code completion and hover documentation, and the compiler points out mistakes early on so you can focus on making your app look amazing.
rundeps    :
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - /*
